name=BatteryPercentage
version=1.0.0
author=Karol
maintainer=Karol <kjakubowski0492@gmail.com>
sentence=Biblioteka do obliczania procentowego naładowania baterii.
paragraph=Obsługuje różne typy baterii, takie jak LiPo, LiIon, NiMH, NiCd, LeadAc, Alkaline i ZincCarbon.
category=Sensors
url=https://github.com/JAQUBA/BatteryPercentage
architectures=*